# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
name: "CI"

on: [push, pull_request]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
    
      - name: Install package under test
        run: poetry install -E cli

      - name: Run tests
        run: poetry run pytest --cov=fast_json_pointer --cov-report lcov tests/ --doctest-modules src/

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: coverage.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}


  test-publish:
    name: "TestPyPI"
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test]
    uses: .github/workflows/pypi.yaml
    with:
      repo: https://test.pypi.org/legacy/
    secrets:
      pypi-token: "${{ secrets.TEST_PYPI_API_TOKEN }}"

  publish:
    name: "PyPI"
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test, test-publish]
    uses: .github/workflows/pypi.yaml
    secrets:
      pypi-token: "${{ secrets.PYPI_API_TOKEN }}"
